### ISSUE TITLE
Automatic Image Generation

### ISSUE THREAD

**Issue by Pusselz** [Extraltodeus/ChatGPT_prompt_machine#1]
Hey, thanks a lot for your great work.
I have an idea what you could add.

I would find it interesting to have prompts automatically forwarded to Midjourney. Then generate the images and download them to save them to a folder.

What is the point of all this? For example, you could generate a lot of stock images and upload them to different websites.

**Comment by Extraltodeus** [comment]
You're welcome!

Well one could adapt it to stable diffusion, midjourney or even directly forward to Dalle2 but overall it's more of another script idea.
